#!/usr/bin/python

import sys
import getopt
import re
from gateway import PassiveGateway
from log import Log, UDPWriter, StandardWriter

DISPATCHER = 'DISPATCHER'
EVENT_HANDLER = 'EVENT_HANDLER'
CPU_INTENSITY = 'CPU_INTENSITY'
IO_INTENSITY = 'IO_INTENSITY'
TEST_MANAGER_ADDRESS = 'TEST_MANAGER_ADDRESS'
LOG_SERVER_PORT = 'LOG_SERVER_PORT'
NAMESERVICE_PORT = 'NAMESERVICE_PORT'
POOL_SIZE = 'POOL_SIZE'

def usage():
    print(
    """
    usage: ./gateway [<options>...]

    OPTIONS
        -h
            Show this message.

        -d, --dispatcher <architecture>
            The architecture of the event dispatcher. Can be one of the following:
                serial
                preemptive (disabled)
                cooperative (disabled)

        -e, --eventhandler <architecture>
            The architecture of the event handler. Same alternatives as for the
            dispatcher.

        -c, --cpu <value>
            The CPU intensity each event induce. Value between 0 and 1.

        -i, --io <value>
            The I/O intensity each event induce. Value between 0 and 1.

        -t, --testmanager <address>
            The IP address (no port) of the test manager.

        -l, --logserver <port>
            The port of the log server.

        -n, --nameservice <port>
            The port of the nameservice.

        -g, --loglevel <value>
            The log level to print to stdout. One of 0 (DEBUG), 1 (INFO)
            (default) and 2 (ERROR).

        -p, --poolsize <value>
            Thread pool size.
    """
)

def parse_address(address_string):
    """ Parses address on the format <address>:<port> and returns a tuple.
    """

    m = re.match(r'^(\d+\.\d+\.\d+\.\d+)$', address_string)

    if m:
        addr = m.group(1)
        return addr
    else:
        raise AttributeError('Not a valid address format')

def verify_parameters(configuration):
    valid_parameters = [
        DISPATCHER,
        EVENT_HANDLER,
        CPU_INTENSITY,
        IO_INTENSITY,
        TEST_MANAGER_ADDRESS,
        LOG_SERVER_PORT,
        NAMESERVICE_PORT,
        POOL_SIZE]

    return all(param in configuration for param in valid_parameters)

def get_configuration_string(configuration):
    result = ''
    for param in configuration:
        result += '  {}: {}\n'.format(param, configuration[param])
    return result

def main(argv):
    logger = Log.get_logger(__name__, StandardWriter)
    log_level = Log.LEVEL_INFO # default

    try:
        opts, args = getopt.getopt(
            argv,
            'hd:e:c:i:t:l:n:g:p:',
            [
                'dispatcher=',
                'eventhandler=',
                'cpu=',
                'io=',
                'testmanager=',
                'logserver=',
                'nameservice=',
                'loglevel=',
                'poolsize='
            ])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    configuration = {}

    for opt, arg in opts:
        if opt == '-h':
            usage()
            return
        if opt in ('-d', '--dispatcher'):
            configuration[DISPATCHER] = arg
        if opt in ('-e', '--eventhandler'):
            configuration[EVENT_HANDLER] = arg
        if opt in ('-c', '--cpu'):
            configuration[CPU_INTENSITY] = float(arg)
        if opt in ('-i', '--io'):
            configuration[IO_INTENSITY] = float(arg)
        if opt in ('-t', '--testmanager'):
            configuration[TEST_MANAGER_ADDRESS] = parse_address(arg)
        if opt in ('-l', '--logserver'):
            configuration[LOG_SERVER_PORT] = int(arg)
        if opt in ('-n', '--nameservice'):
            configuration[NAMESERVICE_PORT] = int(arg)
        if opt in ('-g', '--loglevel'):
            log_level = int(arg)
        if opt in ('-p', '--poolsize'):
            configuration[POOL_SIZE] = int(arg)

    Log.config(level=log_level)
    logger.debug('Read configuration: \n{}',
            get_configuration_string(configuration))

    if verify_parameters(configuration):
        writer = UDPWriter((
            configuration[TEST_MANAGER_ADDRESS],
            configuration[LOG_SERVER_PORT]))
        Log.config(default_writer=writer)

        gw = PassiveGateway(
                (
                    configuration[TEST_MANAGER_ADDRESS],
                    configuration[NAMESERVICE_PORT]
                ),
                configuration[CPU_INTENSITY],
                configuration[IO_INTENSITY])
        gw.start_server()

        if gw.verify_configuration(configuration):
            logger.info('Config OK')
            gw.register_devices()
            logger.info('Waiting for testmanager to start test...')
            gw.wait_for_start()
        else:
            logger.error('Config not OK! Closing...')
            gw.close_server()
            sys.exit(2)

        logger.info('Start')

        try:
            while True:
                gw.get_events()
        except KeyboardInterrupt:
            gw.close_server()

    else:
        usage()
        return

if __name__ == '__main__':
    main(sys.argv[1:])
