#!/usr/bin/python


import sys
import getopt
import re
from log import now, Log, LogServer, UDPWriter
from device import PassiveDevice
from testmanager import TestManager


logger = Log.get_logger(__name__)

NAMESERVICE_PORT = 0
LOG_SERVER_PORT = 0

DEVICE_QUANTITY = 'DEVICE_QUANTITY'
DEVICE_FREQUENCY = 'DEVICE_FREQUENCY'
DEVICE_DELAY = 'DEVICE_DELAY'
DISPATCHER = 'DISPATCHER'
EVENT_HANDLER = 'EVENT_HANDLER'
CPU_INTENSITY = 'CPU_INTENSITY'
IO_INTENSITY = 'IO_INTENSITY'
DEVICE_TYPE = 'DEVICE_TYPE'
LOG_LEVEL = 'LOG_LEVEL'


def usage():
    print(
    """
    usage: ./run_test [<options>...]

    OPTIONS
        -h
            Show this message

        -q, --quantity <value>
            The number of simulated devices to run in the test.

        -f, --frequency <value>
            The frequency in which one device creates new events, expressed in
            times / second.

        -l, --delay <value>
            The delay expressed in seconds in which one device waits to sends a
            response upon a request.

        -d, --dispatcher <architecture>
            The architecture of the event dispatcher. Can be one of the following:
                serial
                preemptive (disabled)
                cooperative (disabled)

        -e, --eventhandler <architecture>
            The architecture of the event handler. Same alternatives as for the
            dispatcher.

        -c, --cpu <value>
            The CPU intensity each event induce. Value between 0 and 1.

        -i, --io <value>
            The I/O intensity each event induce. Value between 0 and 1.

        -g, --loglevel <value>
            The log level to print to stdout. One of 0 (DEBUG), 1 (INFO)
            (default) and 2 (ERROR).
    """
    )


def parse_time(time_str):
    match = re.match(r'^(\d+h)?(\d+m)?(\d+s)?$', time_str)

    if match:
        h = match.group(1)
        m = match.group(2)
        s = match.group(3)

        h = int(h[:-1]) if h is not None else 0
        m = int(m[:-1]) if m is not None else 0
        s = int(s[:-1]) if s is not None else 0

        return ((h * 3600) + (m * 60) + s) * 1000
    else:
        return 0


def main(argv):
    configuration = {}
    configuration[LOG_LEVEL] = Log.LEVEL_INFO # default
    duration = 0

    if len(argv) == 0:
        usage()
        return

    try:
        opts, args = getopt.getopt(
            argv,
            'hq:f:l:d:e:c:i:t:g:',
            [
                'quantity=',
                'frequency=',
                'delay=',
                'dispatcher=',
                'eventhandler=',
                'cpu=',
                'io=',
                'duration=',
                'loglevel='
            ])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    for opt, arg in opts:
        if opt == '-h':
            usage()
            return
        if opt in ('-q', '--quantity'):
            configuration[DEVICE_QUANTITY] = int(arg)
        if opt in ('-f', '--frequency'):
            configuration[DEVICE_FREQUENCY] = float(arg)
        if opt in ('-l', '--delay'):
            configuration[DEVICE_DELAY] = float(arg)
        if opt in ('-d', '--dispatcher'):
            configuration[DISPATCHER] = arg
        if opt in ('-e', '--eventhandler'):
            configuration[EVENT_HANDLER] = arg
        if opt in ('-c', '--cpu'):
            configuration[CPU_INTENSITY] = float(arg)
        if opt in ('-i', '--io'):
            configuration[IO_INTENSITY] = float(arg)
        if opt in ('-t', '--duration'):
            duration = parse_time(arg)
        if opt in ('-g', '--loglevel'):
            configuration[LOG_LEVEL] = int(arg)

    configuration[DEVICE_TYPE] = PassiveDevice

    tm = TestManager(NAMESERVICE_PORT, configuration)
    ls = LogServer(('', LOG_SERVER_PORT), tm)

    writer = UDPWriter(ls.hostname())
    Log.config(level=configuration[LOG_LEVEL], default_writer=writer)

    ls.start()

    logger.info('Waiting for gateway...')
    if tm.verify_gateway(ls.hostname()):
        tm.save_configuration(DEVICE_QUANTITY,
                configuration[DEVICE_QUANTITY])
        tm.save_configuration(DEVICE_FREQUENCY,
                configuration[DEVICE_FREQUENCY])
        tm.save_configuration(DEVICE_DELAY,
                configuration[DEVICE_DELAY])
        tm.save_configuration(DISPATCHER,
                configuration[DISPATCHER])
        tm.save_configuration(EVENT_HANDLER,
                configuration[EVENT_HANDLER])
        tm.save_configuration(CPU_INTENSITY,
                configuration[CPU_INTENSITY])
        tm.save_configuration(IO_INTENSITY,
                configuration[IO_INTENSITY])

        tm.sync_time()
        end_time = now() + duration
        tm.start_test()

        if duration > 0:
            logger.info('Starting test with timeout {} ms', duration)
        else:
            logger.info('Starting test')

        try:
            while duration == 0 or now() < end_time:
                tm.handle_event_message()

            logger.info('Timeout')
        except KeyboardInterrupt:
            pass
        finally:
            tm.end_test()
            ls.close()
    else:
        logger.error('Gateway verification failed')
        tm.end_test()
        ls.close()


if __name__ == '__main__':
    main(sys.argv[1:])
